# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gemm_simple.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11gemm_simple.proto\x12\x0bgemm_simple\"B\n\x11MatMulInitRequest\x12\t\n\x01m\x18\x01 \x01(\x05\x12\t\n\x01k\x18\x02 \x01(\x05\x12\t\n\x01n\x18\x03 \x01(\x05\x12\x0c\n\x04pref\x18\x04 \x01(\t\"@\n\x12MatMulInitResponse\x12\x13\n\x0boperationId\x18\x01 \x01(\x05\x12\x15\n\restimatedTime\x18\x02 \x01(\x05\"S\n\rMatricesInput\x12\x13\n\x0boperationId\x18\x01 \x01(\x05\x12\t\n\x01m\x18\x02 \x01(\x05\x12\t\n\x01k\x18\x03 \x01(\x05\x12\t\n\x01n\x18\x04 \x01(\x05\x12\x0c\n\x04\x64\x61ta\x18\x05 \x03(\x02\"G\n\x0cMatrixOutput\x12\x13\n\x0boperationId\x18\x01 \x01(\x05\x12\t\n\x01m\x18\x02 \x01(\x05\x12\t\n\x01n\x18\x03 \x01(\x05\x12\x0c\n\x04\x64\x61ta\x18\x04 \x03(\x02\x32\xa3\x01\n\x06MatMul\x12P\n\rRequestMatMul\x12\x1e.gemm_simple.MatMulInitRequest\x1a\x1f.gemm_simple.MatMulInitResponse\x12G\n\x0eMatrixMultiply\x12\x1a.gemm_simple.MatricesInput\x1a\x19.gemm_simple.MatrixOutputb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'gemm_simple_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_MATMULINITREQUEST']._serialized_start=34
  _globals['_MATMULINITREQUEST']._serialized_end=100
  _globals['_MATMULINITRESPONSE']._serialized_start=102
  _globals['_MATMULINITRESPONSE']._serialized_end=166
  _globals['_MATRICESINPUT']._serialized_start=168
  _globals['_MATRICESINPUT']._serialized_end=251
  _globals['_MATRIXOUTPUT']._serialized_start=253
  _globals['_MATRIXOUTPUT']._serialized_end=324
  _globals['_MATMUL']._serialized_start=327
  _globals['_MATMUL']._serialized_end=490
# @@protoc_insertion_point(module_scope)
